[project]
name = "reinforcement-learning-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.3",
    "ipykernel>=7.2.0",
    "rich>=14.3.3",
    "stable-baselines3>=2.7.1",
]
